
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=palermo
      - POSTGRES_USER=palermo_user
      - POSTGRES_PASSWORD=fargenius
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5433
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             chmod -R 755 /app/static &&
             chmod -R 755 /app/media &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=palermo
      - POSTGRES_USER=palermo_user
      - POSTGRES_PASSWORD=fargenius
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
      - front
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./nginx.conf:/etc/nginx/nginx.conf
  front:
    build:
      context: "../front/palermo/"
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - app
    ports:
      - "3000:3000"
    expose:
      - "3000"


volumes:
  postgres_data:

