services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_DB=palermo
      - POSTGRES_USER=palermo_user
      - POSTGRES_PASSWORD=fargenius
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5433
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='root').exists() or User.objects.create_superuser('root', 'root@example.com', '1')\" | python manage.py shell &&
            python manage.py runserver 0.0.0.0:8000"




  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=palermo
      - POSTGRES_USER=palermo_user
      - POSTGRES_PASSWORD=fargenius
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: