# Generated by Django 5.1.2 on 2025-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPGHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='header/banners/')),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_color', models.ImageField(blank=True, null=True, upload_to='colors/')),
                ('color1', models.ImageField(blank=True, null=True, upload_to='colors/')),
                ('color2', models.ImageField(blank=True, null=True, upload_to='colors/')),
                ('color3', models.ImageField(blank=True, null=True, upload_to='colors/')),
            ],
            options={
                'verbose_name': 'AboutPG Header',
                'verbose_name_plural': 'AboutPG Headers',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='HomePageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='header/banners/')),
                ('text1_ru', models.TextField()),
                ('text1_en', models.TextField()),
                ('text2_ru', models.TextField()),
                ('text2_en', models.TextField()),
                ('color_image_1', models.ImageField(upload_to='header/color/')),
                ('color_image_2', models.ImageField(upload_to='header/color/')),
            ],
            options={
                'verbose_name': 'HomePG Header',
                'verbose_name_plural': 'HomePG Headers',
            },
        ),
        migrations.CreateModel(
            name='HomePGAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('text_ru', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'verbose_name': 'ГлавнаяСТ-о нас',
                'verbose_name_plural': 'ГлавнаяСТ-о нас',
            },
        ),
        migrations.CreateModel(
            name='HomePGOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offers-images/')),
                ('title_ru', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
            ],
            options={
                'verbose_name': 'ГлавнаяСТ-услуги',
                'verbose_name_plural': 'ГлавнаяСТ-offers',
            },
        ),
        migrations.CreateModel(
            name='OurData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title_ru', models.CharField(max_length=100)),
                ('contact_title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('address_ru', models.CharField(max_length=150)),
                ('address_en', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('latitude', models.PositiveIntegerField(blank=True, null=True)),
                ('longitude', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Our Contact',
                'verbose_name_plural': 'Our Contacts',
            },
        ),
        migrations.CreateModel(
            name='OurSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='social/')),
                ('link', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Our Social',
                'verbose_name_plural': 'Our Socials',
            },
        ),
    ]
