# Generated by Django 5.1.2 on 2025-02-26 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPGBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='about/images/')),
            ],
            options={
                'verbose_name': 'AboutPG Blog',
                'verbose_name_plural': 'AboutPG Blogs',
            },
        ),
        migrations.CreateModel(
            name='BlogPGHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='header/banners/')),
                ('body1_text_ru', models.CharField(max_length=122)),
                ('body1_text_en', models.CharField(blank=True, max_length=122, null=True)),
                ('body1_description_ru', models.TextField(blank=True)),
                ('body1_description_en', models.TextField(blank=True, null=True)),
                ('body2_text_ru', models.CharField(max_length=122)),
                ('body2_text_en', models.CharField(blank=True, max_length=122, null=True)),
                ('body2_video', models.FileField(blank=True, null=True, upload_to='blogs/header/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Products Category',
            },
        ),
        migrations.CreateModel(
            name='Consultations1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='services/')),
            ],
            options={
                'verbose_name': 'Consultations1',
                'verbose_name_plural': 'Consultations1',
            },
        ),
        migrations.CreateModel(
            name='Consultations2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('color', models.ImageField(null=True, upload_to='services/')),
                ('text_ru', models.CharField(max_length=255)),
                ('text_en', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Consultations2',
                'verbose_name_plural': 'Consultations2',
            },
        ),
        migrations.CreateModel(
            name='Consultations3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='services/')),
            ],
            options={
                'verbose_name': 'Consultations3',
                'verbose_name_plural': 'Consultations3',
            },
        ),
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/')),
                ('name', models.CharField(blank=True, max_length=122, null=True)),
            ],
            options={
                'verbose_name': 'Our Works',
                'verbose_name_plural': 'Our Works',
            },
        ),
        migrations.CreateModel(
            name='OurWorksTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Our Works Title',
                'verbose_name_plural': 'Our Works Titles',
            },
        ),
        migrations.CreateModel(
            name='ServicePGClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients/')),
            ],
            options={
                'verbose_name': 'ServicePG Clients',
                'verbose_name_plural': 'ServicePG Clients',
            },
        ),
        migrations.CreateModel(
            name='ServicePGHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='header/banners/')),
                ('body1_text_ru', models.CharField(max_length=222)),
                ('body1_text_en', models.CharField(blank=True, max_length=222, null=True)),
                ('body1_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('body1_description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('body2_text_ru', models.CharField(max_length=222)),
                ('body2_text_en', models.CharField(blank=True, max_length=222, null=True)),
                ('body2_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('body2_description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('body2_image', models.ImageField(upload_to='services/')),
            ],
            options={
                'verbose_name': 'ServicePG Header',
                'verbose_name_plural': 'ServicePG Headers',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=122, null=True)),
                ('avatar', models.ImageField(upload_to='testimonials/avatar/')),
                ('text', models.TextField()),
                ('marks', models.IntegerField(default=0)),
                ('image1', models.ImageField(upload_to='testimonials/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.AlterModelOptions(
            name='homepgabout',
            options={'verbose_name': 'HomePG about', 'verbose_name_plural': 'HomePG about'},
        ),
        migrations.AlterModelOptions(
            name='homepgoffers',
            options={'verbose_name': 'HomePG Offer', 'verbose_name_plural': 'HomePG Offers'},
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=155)),
                ('name_en', models.CharField(blank=True, max_length=155, null=True)),
                ('body_ru', models.TextField()),
                ('body_en', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to='products/main_image/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
