# Generated by Django 5.1.2 on 2025-03-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicepgclientstitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='header/banners/')),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('minititle_ru', models.CharField(max_length=255)),
                ('minititle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('color_image_1', models.ImageField(upload_to='header/color/', verbose_name='Цветное изображение 1')),
                ('color_image_2', models.ImageField(upload_to='header/color/', verbose_name='Цветное изображение 2')),
                ('about_title_ru', models.CharField(max_length=255)),
                ('about_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('about_description_ru', models.TextField(blank=True, null=True)),
                ('about_description_en', models.TextField(blank=True, null=True)),
                ('image1_title_ru', models.CharField(max_length=255)),
                ('image1_title_en', models.CharField(max_length=255)),
                ('image1_description_ru', models.TextField(blank=True, null=True)),
                ('image1_description_en', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='header/color/', verbose_name='Цветное изображение 1')),
                ('image2_title_ru', models.CharField(max_length=255)),
                ('image2_title_en', models.CharField(max_length=255)),
                ('image2_description_ru', models.TextField(blank=True, null=True)),
                ('image2_description_en', models.TextField(blank=True, null=True)),
                ('image2', models.ImageField(upload_to='header/color/', verbose_name='Цветное изображение 1')),
                ('image3_title_ru', models.CharField(max_length=255)),
                ('image3_title_en', models.CharField(max_length=255)),
                ('image3_description_ru', models.TextField(blank=True, null=True)),
                ('image3_description_en', models.TextField(blank=True, null=True)),
                ('image3', models.ImageField(upload_to='header/color/', verbose_name='Цветное изображение 1')),
                ('image4_title_ru', models.CharField(max_length=255)),
                ('image4_title_en', models.CharField(max_length=255)),
                ('image4_description_ru', models.TextField(blank=True, null=True)),
                ('image4_description_en', models.TextField(blank=True, null=True)),
                ('image4', models.ImageField(upload_to='header/color/', verbose_name='Цветное изображение 1')),
            ],
        ),
        migrations.AlterModelOptions(
            name='homepageheader',
            options={'verbose_name': '🏠 Заголовок главной страницы', 'verbose_name_plural': '🏠 Заголовки главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='homepgabout',
            options={'verbose_name': 'О нас (главная страница)', 'verbose_name_plural': 'О нас (главная страница)'},
        ),
        migrations.AlterModelOptions(
            name='homepgoffers',
            options={'verbose_name': 'Предложение (главная страница)', 'verbose_name_plural': 'Предложения (главная страница)'},
        ),
        migrations.AlterField(
            model_name='homepageheader',
            name='color_image_1',
            field=models.ImageField(upload_to='header/color/', verbose_name='Цветное изображение 1'),
        ),
        migrations.AlterField(
            model_name='homepageheader',
            name='color_image_2',
            field=models.ImageField(upload_to='header/color/', verbose_name='Цветное изображение 2'),
        ),
        migrations.AlterField(
            model_name='homepageheader',
            name='text1_en',
            field=models.TextField(verbose_name='Текст 1 (английский)'),
        ),
        migrations.AlterField(
            model_name='homepageheader',
            name='text1_ru',
            field=models.TextField(verbose_name='Текст 1 (русский)'),
        ),
        migrations.AlterField(
            model_name='homepageheader',
            name='text2_en',
            field=models.TextField(verbose_name='Текст 2 (английский)'),
        ),
        migrations.AlterField(
            model_name='homepageheader',
            name='text2_ru',
            field=models.TextField(verbose_name='Текст 2 (русский)'),
        ),
        migrations.AlterField(
            model_name='homepgabout',
            name='text_en',
            field=models.TextField(verbose_name='Текст (английский)'),
        ),
        migrations.AlterField(
            model_name='homepgabout',
            name='text_ru',
            field=models.TextField(verbose_name='Текст (русский)'),
        ),
        migrations.AlterField(
            model_name='homepgabout',
            name='title_en',
            field=models.CharField(max_length=120, verbose_name='Заголовок (английский)'),
        ),
        migrations.AlterField(
            model_name='homepgabout',
            name='title_ru',
            field=models.CharField(max_length=120, verbose_name='Заголовок (русский)'),
        ),
        migrations.AlterField(
            model_name='homepgoffers',
            name='description_en',
            field=models.TextField(verbose_name='Описание (английский)'),
        ),
        migrations.AlterField(
            model_name='homepgoffers',
            name='description_ru',
            field=models.TextField(verbose_name='Описание (русский)'),
        ),
        migrations.AlterField(
            model_name='homepgoffers',
            name='image',
            field=models.ImageField(upload_to='offers-images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='homepgoffers',
            name='title_en',
            field=models.CharField(max_length=120, verbose_name='Заголовок (английский)'),
        ),
        migrations.AlterField(
            model_name='homepgoffers',
            name='title_ru',
            field=models.CharField(max_length=120, verbose_name='Заголовок (русский)'),
        ),
    ]
