# Generated by Django 5.1.2 on 2025-03-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_homepg_alter_homepageheader_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepg',
            options={'verbose_name': '🏠 Главная страница', 'verbose_name_plural': '🏠 Главные страницы'},
        ),
        migrations.AlterField(
            model_name='homepg',
            name='about_description_en',
            field=models.TextField(blank=True, null=True, verbose_name="📄 Описание 'О нас' (EN)"),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='about_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name="📄 Описание 'О нас' (RU)"),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='about_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ℹ️ Заголовок 'О нас' (EN)"),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='about_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ℹ️ Заголовок 'О нас' (RU)"),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='color_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='header/color/', verbose_name='🎨 Цветное изображение 1'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='color_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='header/color/', verbose_name='🎨 Цветное изображение 2'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='📝 Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='📝 Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='header/banners/', verbose_name='🖼 Баннер'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='header/color/', verbose_name='🖼 Изображение 1'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image1_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='🖊 Описание изображения 1 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image1_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='🖊 Описание изображения 1 (RU)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image1_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🏞 Заголовок изображения 1 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image1_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🏞 Заголовок изображения 1 (RU)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='header/color/', verbose_name='🖼 Изображение 2'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image2_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='🖊 Описание изображения 2 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image2_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='🖊 Описание изображения 2 (RU)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image2_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🏞 Заголовок изображения 2 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image2_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🏞 Заголовок изображения 2 (RU)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='header/color/', verbose_name='🖼 Изображение 3'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image3_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='🖊 Описание изображения 3 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image3_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='🖊 Описание изображения 3 (RU)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image3_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🏞 Заголовок изображения 3 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image3_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🏞 Заголовок изображения 3 (RU)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='header/color/', verbose_name='🖼 Изображение 4'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image4_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='🖊 Описание изображения 4 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image4_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='🖊 Описание изображения 4 (RU)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image4_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🏞 Заголовок изображения 4 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='image4_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🏞 Заголовок изображения 4 (RU)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='minititle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🔹 Мини-заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='minititle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🔹 Мини-заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='📌 Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepg',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='📌 Заголовок (RU)'),
        ),
    ]
