# Generated by Django 5.1.2 on 2025-03-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_homepg_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageHeader',
        ),
    ]
